/* JAVA */
public class Main 
{
    public static void main(String[] args) 
    {
        int[] arr = {1, 2, 3, 4, 5};
        // Imprimir el arreglo
        for (int i = 0; i < arr.length; i++) 
        {
        System.out.print(arr[i] + " ");
        }
    }
}
    /* C++ */
#include <iostream>
using namespace std;
int main() 
{
    int arr[] = {1, 2, 3, 4, 5};
    // Imprimir el arreglo
    for (int i = 0; i < 5; i++) 
    {
        cout << arr[i] << " ";
    }
}
%% PYTHON
#include <iostream>
using namespace std;
int main() 
{
    int arr[] = {1, 2, 3, 4, 5};
    // Imprimir el arreglo
    for (int i = 0; i < 5; i++) 
    {
        cout << arr[i] << " ";
    }
    return 0;
}